parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     CSCWObservatory
    database_user:     root
    database_password: '123456'

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            57b28ec145859f1d606b35100cfdf14827ae4e70